name: Run Backtest

on:
  workflow_dispatch:

permissions: {}

jobs:
  backtest:
    uses: fxquantbench/model-template/.github/workflows/_run_backtest.yml@main
    secrets: inherit
    with:
      repo: ${{ github.repository }}
      model_id: ${{ vars.MODEL_ID }}
      in_sample_start: ${{ vars.IN_SAMPLE_START }}
      in_sample_end: ${{ vars.IN_SAMPLE_END }}
